version: '3'
services:
  analytics_service:
    build: ./
    container_name: analytics_service
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      - analytics_db
    networks:
      - collabvr_network
    env_file:
      - .env

  analytics_db:
    image: postgres:13
    container_name: analytics_db
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    networks:
      - collabvr_network

networks:
  collabvr_network:
    driver: bridge
